INSERT INTO Loggedin (name, password) VALUES ('Antero', 'oretna');
INSERT INTO Loggedin (name, password) VALUES ('Pekka', 'Juhani');
INSERT INTO Loggedin (name, password) VALUES ('Feaasd', 'dsdfa');
INSERT INTO Loggedin (name, password) VALUES ('Koeer', 'ascxzzxc');
INSERT INTO Loggedin (name, password) VALUES ('Niimer', 'sdavasdv');
INSERT INTO Loggedin (name, password) VALUES ('Kauresdf', 'vsdvdvsdv');
INSERT INTO Loggedin (name, password) VALUES ('Halleru', 'noansovnsdoiv');
INSERT INTO Loggedin (name, password) VALUES ('Nipperu', 'kiirasvuosi');
INSERT INTO Loggedin (name, password) VALUES ('Jauajayauau', 'voopirre');
INSERT INTO Loggedin (name, password) VALUES ('Anselmi', 'Antoisauhani');
INSERT INTO Subforum (name, description) VALUES ('banaanipepe', 'Sauhunaama on liikkeellä');
INSERT INTO Subforum (name, description) VALUES ('Makaroonilaatikko', 'Sauhunaama on liikkeelsdfasdfasdfasdasdfasdflä');
INSERT INTO Subforum (name, description) VALUES ('Sudokusuihke', 'Sauhunaama on lisdfasdfsaffsdfikkeellä');
INSERT INTO Subforum (name, description) VALUES ('Vaaran tiellä', 'Sauhunaamfafasda on liikkeellä');
INSERT INTO Thread (subforum, time, topic, starter) VALUES (1, '2015-12-24 10:03:40.853087', 'Harvinaisia pepejä 3SIPULISIPULI€/kpl', 1); 
INSERT INTO Thread (subforum, time, topic, starter) VALUES (2, '2015-12-25 10:03:40.853087', 'SIPULISIPULIHarvinaisia psdvsdavsepejä 3€/kpl', 2); 
INSERT INTO Thread (subforum, time, topic, starter) VALUES (3, '2015-12-26 10:03:40.853087', 'HarvinaSIPULISIPULISIPULIisivsa pepejäsadvsadvsadv 3€/kpl', 3); 
INSERT INTO Thread (subforum, time, topic, starter) VALUES (4, '2015-12-27 10:03:40.853087', 'HarvinaisiadsdavaSIPULISIPULsdfafIsdvsadvvsa pepejä 3€/kpl', 4); 
INSERT INTO Thread (subforum, time, topic, starter) VALUES (1, '2015-12-28 10:03:40.853087', 'sadv pesdvavsdavsSIPULISIPULIdavsdvsdvpejä 3€/kpl', 1); 
INSERT INTO Thread (subforum, time, topic, starter) VALUES (2, '2015-12-29 10:03:40.853087', 'HarviSIPULISIPULInaisadvia asdvsdvasdvpepejä 3€/kpl', 4); 
INSERT INTO Thread (subforum, time, topic, starter) VALUES (3, '2015-12-30 10:03:40.853087', 'Harvinaisdavssdvia pepejä 3€/SIPULIkpl', 6); 
INSERT INTO Thread (subforum, time, topic, starter) VALUES (4, '2015-12-31 10:03:40.853087', 'Harvinaissdvasdavsdavsia peSIPULISIPULIpejä 3€/kpl', 8); 
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on edullisia pepejä', NOW(), 1, 7);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on asdv pepejä',  NOW(), 2, 7);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on edsdavaasvullisia pepejä', NOW(), 3, 7);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on edusvadvsdllisia pepejä', NOW(), 4, 7);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on dav pepejä', NOW(), 5, 7);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on edusdvasdvasdvllisia pepejä', NOW(), 6, 5);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele ettsavasdvasdvsadvasdvä on edullisia pepejä', NOW(), 7, 5);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on edsdvsadvasdvasdvasdullisia pepejä', NOW(), 8, 5);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on eduvsdavsdavsdsllisia pepejä',  NOW(), 9, 8);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että osadvsavsdavasdvsdn edullisia pepejä', NOW(), 1, 7);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että ovsadvasdvn edullisia pepejä',  NOW(), 2, 0);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on evafdvaddullisia pepejä', NOW(), 3, 1);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on evsdvdullisia pepejä', NOW(), 4, 2);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on edullisia pepejä',  NOW(), 5, 3);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on eavdasdullisia pepejä', NOW(), 6, 4);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on eadfvvsvdullisia pepejä', NOW(), 7, 5);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele että on esdvasdvdullisia pepejä', NOW(), 5, 6);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele ettsdvavsdaä on edullisia pepejä', NOW(), 5, 7);
INSERT INTO Message (content, time, author, thread) VALUES ('Perkele etsvdavsadvsadvtä on edullisia pepejä', NOW(), 5, 8);


